### ISSUE TITLE
JSException after clicking on a link inside SelectedTemplate

### ISSUE THREAD

**Issue by sven-n** [Blazored/Typeahead#115] opened 2020-02-21 17:45 UTC
How to reproduce:
1. Create a blazor server-side project with the template in VS 2019 16.4(+)
2. Setup BlazoredTypeahead, like described in your documentation.
3. Add a razor page under "Pages", e.g. "Issue.razor" with the following content:
```
@page "/issue"
<EditForm Model="Model">
    <BlazoredTypeahead 
                        SearchMethod="MySearchAsync"
                        @bind-Value="Model.Foo"
                        EnableDropDown="true"
                        placeholder="Search ..."
                        id="foo">
        <SelectedTemplate Context="item">
            <NavLink href="counter">@item</NavLink>
        </SelectedTemplate>
        <ResultTemplate Context="item">
            @item
        </ResultTemplate>
    </BlazoredTypeahead>
</EditForm>

@code {

    private MyModel Model { get; set; } = new MyModel();

    private Task<IEnumerable<string>> MySearchAsync(string input)
    {
        return Task.FromResult(Enumerable.Range(1, 3).Select(i => $"My Entry {i}"));
    }

    class MyModel
    {
        public string Foo { get; set; }
    }
}
```

4. Edit NavMenu.razor, add a new entry:
```
        <li class="nav-item px-3">
            <NavLink class="nav-link" href="issue">
                <span class="oi oi-list-rich" aria-hidden="true"></span> Test issue
            </NavLink>
        </li>
```

5. Start the app, go to the page "Test issue"
6. Select an item
7. Click on the link which was generated for the current item
8. -> Exception in ```BlazoredTypeahead`2.HandleClickOnMask```:
```
Microsoft.JSInterop.JSException: 'element is null
setFocus@https://localhost:44356/_content/Blazored.Typeahead/blazored-typeahead.js:4:9
beginInvokeJSFromDotNet/r<@https://localhost:44356/_framework/blazor.server.js:8:31421
beginInvokeJSFromDotNet@https://localhost:44356/_framework/blazor.server.js:8:31390
C</e.prototype.invokeClientMethod/<@https://localhost:44356/_framework/blazor.server.js:1:19202
C</e.prototype.invokeClientMethod@https://localhost:44356/_framework/blazor.server.js:1:19173
C</e.prototype.processIncomingData@https://localhost:44356/_framework/blazor.server.js:1:17165
e/this.connection.onreceive@https://localhost:44356/_framework/blazor.server.js:1:10276
A</e.prototype.connect/</</</i.onmessage@https://localhost:44356/_framework/blazor.server.js:1:38091
'
```

Hint:
If you look at the code of ```HandleClickOnMask```, it waits 250 ms from the click to the javascript interop call. During this waiting time, the html element probably got removed at the browser side.

**Comment by chrissainty** [comment] 2020-02-22 18:19
Hi @sven-n, thanks for raising this. The SelectedTemplate isn’t designed to have links inside it. The SelectedTemplate is designed be allow you to format look of the selected item. 

I suspect you’re correct that that the actual exception is being caused by us swapping out elements but I don’t see us supporting this use case. 

@vertonghenb do you have an opinion on this?

**Comment by sven-n** [comment] 2020-02-22 18:29
Thanks for your response. I understand it’s a special use case, but the fix seems to be easy. It requires just an additional null-check at the client side javascript code, isn’t it?

**Comment by sven-n** [comment] 2020-02-22 18:43
I checked the code and it seems it was fixed already, 1 month ago: https://github.com/Blazored/Typeahead/commit/c7805d5979929bde4750b2df4806e0c54b69331f

**Comment by vertonghenb** [comment] 2020-02-23 12:39
Yup that's the fix which will solve this issue.

**Comment by chrissainty** [comment] 2020-02-23 17:52
@sven-n Well, that's handy! :) We'll get this shipped soon.

**Comment by trademark18** [comment] 2020-03-05 03:10
Looks like c7805d5 is just what I need too!

**Comment by chrissainty** [comment] 2020-03-05 09:29
Thanks for letting us know @trademark18. I'm working on a big update to Blazored Modal that I'm trying to get out this week. Once that is done I'll get back over to Typeahead and look to ship a new version.

**Comment by chrissainty** [comment] 2020-03-06 09:17
@sven-n @trademark18 

I'm been working on the fix for this issue this morning, but when I run the sample app in IE11 nothing works for me at all. But I'm also not seeing any errors in the console. I've added [Daddoons Blazor polyfill library](https://github.com/Daddoon/Blazor.Polyfill) as per the instructions in the readme with no joy.

Do you have an example somewhere I could look at that runs?

**Closed** 2020-03-06 10:04 UTC
Labels: bug
