### ISSUE TITLE
Don't blank out the text written by the user

### ISSUE THREAD

**Issue by kirk-mcneil** [Blazored/Typeahead#126] opened 2020-03-30 17:17 UTC
Hi Chris and Blazored community,
I hope everyone is doing well in this odd time.

My user's are searching for an agency name, and if it doesn't exist, they want to create that agency name starting with what they just typed. In order to give them this functionality, I return a new object list with 1 object that has the search text and they have to select that description to get their own text back.  If they don't click what they typed or I return nothing in the list and they click away from the textbox, it is blanked out and there's no way for them to type something that is not in the database already.

This removes the 'No results found' template since I always return something. It doesn't seem like a good solution. I think the best solution would be to leave what they typed there and if nothing is found, leave it.  

Maybe I'm doing something wrong and there is a better solution?
Please let me know!
Thanks,
Kirk

**Comment by vertonghenb** [comment] 2020-03-30 19:03
I'm not sure but I think this is what you're after:
https://github.com/Blazored/Typeahead/issues/55

**Comment by kirk-mcneil** [comment] 2020-03-30 19:37
You nailed it! 

Unfortunately, having a button there doesn't help in this instance. In order for the Agency to get added to the list, they need to fill out a whole bunch of information - which is the reason they are on the page to begin with and the reason for the type-ahead, lookup. We don't want them adding new agencies unless we can't find them in the database. 

I'm using the lookup to give them the ability to add onto what we already have if it's found or allow them to type something new in the same field if it isn't found in the database.
 
Hopefully this makes some sort of sense without knowing the business process.

Here's how I did it in jquery..
![image](https://user-images.githubusercontent.com/58949068/77954213-4f5a3d00-729c-11ea-800a-9bc4dff3ccb5.png)

**Comment by chrissainty** [comment] 2020-03-30 19:49
Hi @kirk-mcneil,
I think I understand what you're trying to do. I think you can achieve it but possibly not the way you were hoping.

We don't leave the search text in the input when focus is lost as the input they typed it into is removed from the DOM when focus is lost. We replace it with the `SelectedTemplate`. I think you can achieve what you're after by adding a button, as per @vertonghenb code in #55, but instead of adding a new entry, it hides the Typeahead and replaces it with a normal `InputText` component. As part of doing this, you can capture the value from the Typeahead and assign it to the new Input.

I haven't tried this, I'm just thinking off the top of my head, but I think it's possible.

**Comment by kirk-mcneil** [comment] 2020-03-30 20:18
Hi @chrissainty 
That makes sense. The solution I have now is to create a list with one new object that has the search text as the name of the agency so they have to select that. 

I was thinking if I could get to a lower level, I would return just the search text as an option to the selectedTemplate in order to fill in the input field. That way the resultTemplate would still show that no results were found in the database but the input field would have the search text they typed. This would be good if they mistyped the name too and had to make a correction instead of re-typing. 

If that's not possible, then having them select the text they searched for as a result is probably my best option.
Thanks!

**Comment by kirk-mcneil** [comment] 2020-03-30 20:26
Here's what it looks like if it's not in the database
![image](https://user-images.githubusercontent.com/58949068/77958561-399c4600-72a3-11ea-97b0-af42d0a2d99a.png)

**Comment by chrissainty** [comment] 2020-03-30 23:18
I think what you're doing is probably the best option for what you're doing.

**Comment by kirk-mcneil** [comment] 2020-03-31 12:55
It's going to require training since it isn't intuitive to select the item you just typed. Maybe I can fill it with javascript.
You can close this if you don't think it's a feature worth pursuing.
Thanks,
Kirk

**Comment by chrissainty** [comment] 2020-03-31 12:59
I more of a matter of what's possible with our design. We've had this discussion and it's just not an easy thing to achieve, or potentially even possible with how things currently work. I'll close this as it's definitely not a bug.

**Closed by chrissainty** 2020-03-31 12:59 UTC
Labels: Bug, Triage
