### ISSUE TITLE
How to get rid of the "clear" Symbol ... "x" on the right site of the input field.

### ISSUE THREAD

**Issue by uwerichter** [Blazored/Typeahead#117] opened 2020-03-03 21:02 UTC
Hi folks,

i can't find how to switch/disable the little "x" that should clear the input list.

Or otherwise what function is to be calles if the user click on the clear "x" Symbol.

**Comment by chrissainty** [comment] 2020-03-04 08:45
Hi @uwerichter, I don't think we give that option as you wouldn't be able to clear the seleted value in the dropdown.

**Comment by chrissainty** [comment] 2020-03-06 08:35
As there hasn't been any further communication I'm going to close this issue. Please reopen if you want to discuss this again.

**Closed by chrissainty** 2020-03-06 08:35 UTC

**Comment by Ghevi** [comment] 2022-04-08 16:07
I know this is 2 years old but if someone need a work around...
I needed to make that items from the lists could not be removed so I added this tag in my component:
`<style>
    .blazored-typeahead__multi-value-clear {
        display: none;
    }
</style>
`
This is just a UI thing so then I just thrown an exception if the user manages to make it reappear on the screen by validating the current list with the starting one.
Since this style is applied globally and I had other places where I used the TypeAhead, I made the component where I place this tag completely disappear when done with the selection and confirmed, so the tag would also be gone and not pollute other places.

@chrissainty I understand that this workaround could make people break the component and then complain unnecessary, tell me if you prefer that i remove this comment.
