### ISSUE TITLE
Tab key clears typed text, loses any highlighted selection

### ISSUE THREAD

**Issue by rgamage** [Blazored/Typeahead#79] opened 2019-11-19 15:14 UTC
After typing text into the input field, hitting Tab key clears all the chars you just entered, and moves focus to the next control in the form.  Moving focus is expected, but clearing the text you've just typed seems odd to me, and will be confusing for users.  Some users may expect Tab to complete the selection (as it does in, for example, Visual Studio/Code intellisense), but they would not expect it to undo the work they just did.

Also, if you enter partial text, then arrow-down to high-light an item in the list, then hit Tab, your selection is not chosen (highlighted item is lost), and your text is cleared.  All your work is undone.

I suggest the control be changed to preserve the text already entered at minimum, and ideally provide a hook for the caller of the control to be able to take their own custom action upon Tab keypress (to select the first item, for example).

**Comment by chrissainty** [comment] 2019-11-19 15:46
This is by design, currently you cannot enter arbitrary text into the typeahead, you must select a result from the suggestions. 

In terms of the behavior of hitting tab, I've just been catching up on things and seen your conversation with @vertonghenb  in #76. The standard behavior of tab is to move focus between controls not select values. I'm not trying to say you shouldn't do it, but I think your scenario is less common. I believe @vertonghenb has given you a way of achieving your goal, did that work ok?

**Comment by rgamage** [comment] 2019-11-19 16:15
I understand you can't enter arbitrary text - you have to enter one of the valid entries in the list.  But I've just entered a valid entry, an exact match to one of the drop-down items.  Now I hit Tab, and my result is lost.  Or Enter, and nothing happens.  Or I arrow down, highlight a valid item, again choosing from the list, and Tab erases my work.  Just seems odd to me.  Definitely won't be popular with my users.  For my particular application, it's meant for power users that are heavily keyboard-biased, they need a UI that helps them enter data quickly, without requiring mousing down and clicking for every data field.  That's not possible with this component in its current form.  "No mousy, no worky."

As for @vertonghenb 's suggested fix, I am new to Git (I'm a TFS dinosaur), so still trying to understand how I can try out his changes.  It appears this is a PR on a different fork of what I cloned.  Just not sure of the steps to take to get that version to my machine to test.

Thanks for all the quick feedback/discussion on this, not trying to be a pain, really want Blazor to succeed, and having great components like this work 'out of the box' easily is a big part of that.

**Comment by chrissainty** [comment] 2019-11-19 16:35
But until you actually select a entry from the list by selecting it from the suggestions and pressing enter, you have only entered arbitrary text as far as the control is concerned. We use this control at my work with great success (my team build large scale repairs and maintenance software, lots of data entry and heavy keyboard use) our users are happy with this behavior.

@vertonghenb suggestion doesn't require any changes to this library, it was a change to how you bind your value to the control.

**Comment by rgamage** [comment] 2019-11-19 16:56
Ok, still not quite understanding your users' workflow - can you describe the exact sequence of keyboard strokes that allows them to enter, and select a value from the list and continue on with entering data in the form, without using the mouse?  I must be missing something, sorry for my dull-headedness. 

As for @vertonghenb 's changes, he presented a pull request (#77) that triggered a Select upon hitting the Enter key.  That's the code I wanted to try, along with his suggestion for binding to OnValueChanged.  I figured if the user can type the value they want, hit Enter (which would select the only remaining item), then my code could trigger on this selection and take some action.  But without his pull request code changes to the component, hitting Enter key does nothing, even if there is only one item remaining in the list.

**Comment by chrissainty** [comment] 2019-11-19 17:06
No problem, text chat is a bit of a nightmare when trying to understand things! :)

A user would tab into the control and start typing their search term, 99% of the time they don't type in the whole phase they will just use the arrow keys to highlight the suggestion they want, hit enter and tab out. They are normally in and out in a few seconds depending on the user and the length of there search term.

My apologies, I forgot about that change. Its now merged so will go out with the next version which I want to get out sometime this week.

**Comment by rgamage** [comment] 2019-11-19 17:25
Ok, that makes sense, thanks.  One minor thing I noticed when replicating that workflow, Enter selects the item and hides the drop-down, but doesn't return focus to the input box.  You need to then Tab once to focus on the typeahead again, and Tab again to focus on the next control (e.g. submit button).  So your sequence of type chars, hit Enter, hit Tab would actually be type chars, hit Enter, hit Tab, hit Tab again.  Not a big deal but would be nice if the control retained focus after hitting the Enter key.

**Comment by chrissainty** [comment] 2019-11-20 17:56
Thanks for pointing that out, I think that's a regression from our last big release. I'll get that fixed.

**Comment by chrissainty** [comment] 2019-11-23 14:49
I think we're about done one this one so I'm going to close this issue as a won't fix.

**Closed by chrissainty** 2019-11-23 14:49 UTC
Labels: By Design, wontfix

**Comment by CenterOfGravity** [comment] 2022-05-21 18:51
Hi. thank you
Is there a way of not clearing the input text when clicking or tabbing inside of the input element?
