### ISSUE TITLE
Tab Selection

### ISSUE THREAD

**Issue by mivandoni** [Blazored/Typeahead#245] opened 2021-09-13 14:57 UTC
Most user are used to select data from comboBoxes using arrows + tab key.
Here I can select from list only using mouse or arrows +enter if using keyboard.
is it possible to add the selection with tab?

Best regards

**Comment by chrissainty** [comment] 2021-09-14 06:21
Closing as a duplicate of #197

**Closed by chrissainty** 2021-09-14 06:21 UTC
Labels: Triage, Feature Request
