### ISSUE TITLE
Is there an event for when selected item is changed

### ISSUE THREAD

**Issue by nssidhu** [Blazored/Typeahead#146] opened 2020-07-11 02:55 UTC
I am looking to build cascading Drop downs for Country, City & State. of Car Make, Model etc..
Is there an event to which i can hook into to watch for change in Country so that i can filter the States for the selected country and blank out the cities and repopulate cities once the state is selected ?

**Comment by chrissainty** [comment] 2020-07-13 09:29
Closed as duplicate of #147

**Closed by chrissainty** 2020-07-13 09:29 UTC
Labels: Feature Request, Triage
